"""initial schema

Revision ID: eb916e336f33
Revises: 
Create Date: 2021-06-25 19:30:14.506296

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'eb916e336f33'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource',
    sa.Column('resource_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.PrimaryKeyConstraint('resource_id'),
    sa.UniqueConstraint('resource_id')
    )
    op.create_table('pool',
    sa.Column('pool_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('resource_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('eta', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.resource_id'], ),
    sa.PrimaryKeyConstraint('pool_id')
    )
    op.create_table('request',
    sa.Column('request_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('resource_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.resource_id'], ),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_table('allocation',
    sa.Column('allocation_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('request_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('pool_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['pool_id'], ['pool.pool_id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['request.request_id'], ),
    sa.PrimaryKeyConstraint('allocation_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('allocation')
    op.drop_table('request')
    op.drop_table('pool')
    op.drop_table('resource')
    # ### end Alembic commands ###
